### ISSUE TITLE
Questions RNSB metric

### ISSUE THREAD

**Issue by elaisa91** [dccuchile/wefe#5]
Hi,
I would ask you some questions about WEFE in order to calculate bias with RNSB.

I am using two target sets and two attribute sets and running queries in this form: Query([target1_array, target2_array],[positive_attribute_array, negative_attribute_array], [ntarget1, ntarget2], [nattribute1, nattribute2]). For attributes I have 26 or 50 items in total. I am working with 3 different word embedding models.
My questions are:
1. Why am I obtaining the same results with different runnings?
2. Why am I obtaining very different results with respect to the model used with the same words? For example, I have in most cases RNSB = 0.20 from one model and RNSB = 0.60 / 0.70 for the others. It seems strange.

I read the source code but I don't understand. Maybe I have a problem with my data.

Thank you very much.

Best regards,
Elisabetta Triolo.

**Comment by pabloBad** [comment]
Hi @elaisa91 

> Why am I obtaining the same results with different runnings?

I'm not very clear on what's going on here. 
So far, all the executions should render different results as the sentiments classifier is trained on each execution.
Maybe I would need more context like the queries or models to figure out what is happening.

> Why am I obtaining very different results with respect to the model used with the same words? For example, I have in most cases RNSB = 0.20 from one model and RNSB = 0.60 / 0.70 for the others. It seems strange.

This could be happening because the classifier detects that the negative feelings of the target word embeddings are distributed very differently from a uniform distribution in the embeddings models you mention. 
In this case, the metric would be working well.
But it can also be a result of the classifier not being able to accurately train how to distinguish the sentiments from the attributes because there are so few of them. In that case, it might be worth trying with the positive and negative word sets of Bing-Liu (included in the datasets module) as attributes and see if there are significant changes in the results.

Probably next week I can check what is happening in your first question.

Cheers, 
Pablo.

**Comment by elaisa91** [comment]
Hi @pabloBad,
Thank you for answer.

Respect to the first question, I have a word2vec model loaded with gensim KeyedVectors.load(file)and two fastText model loaded with gensim fasttext.load_facebook_vectors(file).  As target and attribute words I have sets like in the example image: 
![example](https://user-images.githubusercontent.com/22596798/97558469-74529200-19dc-11eb-893b-fd63de8c932b.png)

Respect to the second question, ok I will try to use Bing-Liu word sets and to observe accuracy of the model.

Best regards,
Elisabetta.

**Comment by pabloBad** [comment]
Hi @elaisa91 

Thank you for putting me in context. 
This week I will be seeing what causes different executions to return the same results.

Cheers, 
Pablo.

**Comment by elaisa91** [comment]
Hi @pabloBad,
do you have any news about my question? 

Best regards,
Elisabetta.

**Comment by pabloBad** [comment]
Hi @elaisa91 ,

Sorry for the delay. 
During the last weeks I was refactoring the code a little bit, but today I finished.
I can probably have an answer between today and the beginning of next week. 


Cheers,
Pablo.

**Comment by pabloBad** [comment]
Hi @elaisa91 

I've been checking out what you asked about.
I executed the query using RNSB on two different embeddings according to the following code.

- First I created the query with the words that you sent.
```python
from wefe.query import Query
from wefe.word_embedding_model import WordEmbeddingModel
from wefe.metrics import RNSB

target_1 = ['chimica', 'fisica', 'biologia', 'biofisica', 'ingegneria', 'astronomia', 'biochimica', 'neuroscienza', 'scienza', 'tecnologia', 'Einstein', 'NASA', 'esperimento']
target_2 = ['poesia', 'arte', 'danza', 'litteratura', 'romanzo', 'sinfonia', 'dramma', 'scultura', 'scolpire', 'danzare', 'Shakespeare', 'filosofia', 'lettere', 'storia']
attr_1 = ['maschio', 'maschile', 'uomo', 'ragazzo', 'fratello', 'lo', 'gli', 'figlio', 'padre', 'zio', 'nonno']
attr_2 = ['femmina', 'femminile', 'donna', 'ragazza', 'sorella', 'la', 'le', 'figlia', 'madre', 'zia', 'nonna']

query = Query([target_1, target_2], [attr_1, attr_2], ['Science', 'Arts'],
              ['Male', 'Female'])

```
- Then I loaded a Italian word2vec model, obtained from: https://mlunicampania.gitlab.io/italian-word2vec/

```python
w2v = WordEmbeddingModel(KeyedVectors.load('path_to_word2vec'), 'word2vec')
```

- And then I ran 10 times the query using RNSB:

```python
rnsb = RNSB()

for i in range(10):
    rnsb_reuslts = rnsb.run_query(query, w2v)
    print(rnsb_reuslts['result'])
```

- The results were:

```python
0.0684664166267513
0.027322335152760956
0.051429714130663565
0.03713725401278996
0.011228325663632863
0.06032404123572606
0.09282894369416236
0.09875662587419642
0.023125534453586317
0.07207800440569666
```

- As you can see, each execution returned a different result.
   I also repeated the same test using Fasttext (obtained from https://fasttext.cc/docs/en/crawl-vectors.html)

```python 
from gensim.models import FastText

fast_ita_model = FastText.load_fasttext_format('path_to_fast', 'FastText)

fast_ita = WordEmbeddingModel(fast_ita_model.wv, 'fast')
rnsb = RNSB()

for i in range(10):
    rnsb_reuslts = rnsb.run_query(query, fast_ita)
    print(rnsb_reuslts['result'])
```

- The results were:

```python
0.004174320281331193
0.004088401497143336
0.004867177730217962
0.004188704703686218
0.0052078055138493964
0.002973901974761094
0.0027211448016727646
0.005182092106649754
0.004143101645025904
0.0057364218889089285
```

- In this test, each execution also produced different results. 

According to these tests, you should not be having the behavior described in the first question, since nowhere in the code is a random seed or something similar implemented (although this is planned to provide a possibility of repeating the experiments).
At this point, you may have some problem in your code, although it is not very clear to me what the problem may be.

It is also clear that what you said in your second question is true. word2vec has orders of magnitude greater than that detected by RNSB in FastText.

I don't think this is a problem, since what it indicates is that the metric simply does not detect as much bias in Fast with respect to the first model.
https://github.com/dccuchile/wefe/blob/1d87a545a556bbc9d55eaa44bf888d6b8410fe4f/wefe/metrics/RNSB.py#L171

In the first version I added a num_iterations parameter to run_query in RNSB that repeats the tests as many times as you indicate and then averages the scores. Maybe this will help you to get more reliable results.

I hope this helps you. 
Anyway, I'll keep an eye out if you have any more questions.

Cheers, 
Pablo.

**Comment by elaisa91** [comment]
Hi @pabloBad,
Thank you very much! 

You're right, I've tried to execute the same code and it works.
I noticed that the problem appears when I try to calculate bias with different models like that:

`def exec_metric(metric, models, queries, aggregation):
    df = None
    if (metric == 'RNSB'):
        negative_sentiment = {}
        if models and queries:
            rnsb = RNSB()
            results = []
            query_names = []
            # esegue le query singolarmente 
            for query in queries:
                for model in models:
                    result = rnsb.run_query(query,
                                            model,
                                            num_iterations = 5)
                    result['model_name'] = model.model_name_
                    results.append(result)
                    # IT CONTINUES.....`
Here "model" is a wefe.WordEmbeddingModel and query is wefe.Query

I noticed that in this case the value of "result['result']" is still tha same for different runnings. 

Bias results are always the same in different runnings even using:
`run_queries(RNSB,
                             queries,
                             models,
                             metric_params={'num_iterations': 5},
                             aggregate_results=True,
                             aggregation_function='abs_avg',
                             return_only_aggregation = aggregation,
                             queries_set_name='Total Queries')`

Maybe I have problems with my code...I don't know why it is happening. 

Thank you again for your attention and patience.

Elisabetta.

**Comment by pabloBad** [comment]
Hi @elaisa91 ,

It is indeed strange that your code still renders the same results in different executions.
I tried again, now with run_queries and could not replicate what is happening to you.

I attach the code so you can compare it.

```python
from gensim.models import FastText
from gensim.models.keyedvectors import KeyedVectors

from wefe.query import Query
from wefe.word_embedding_model import WordEmbeddingModel
from wefe.metrics import RNSB
from wefe.utils import run_queries



target_1 = ['chimica', 'fisica', 'biologia', 'biofisica', 'ingegneria', 'astronomia', 'biochimica', 'neuroscienza', 'scienza', 'tecnologia', 'Einstein', 'NASA', 'esperimento']
target_2 = ['poesia', 'arte', 'danza', 'litteratura', 'romanzo', 'sinfonia', 'dramma', 'scultura', 'scolpire', 'danzare', 'Shakespeare', 'filosofia', 'lettere', 'storia']
attr_1 = ['maschio', 'maschile', 'uomo', 'ragazzo', 'fratello', 'lo', 'gli', 'figlio', 'padre', 'zio', 'nonno']
attr_2 = ['femmina', 'femminile', 'donna', 'ragazza', 'sorella', 'la', 'le', 'figlia', 'madre', 'zia', 'nonna']

query = Query([target_1, target_2], [attr_1, attr_2], ['Science', 'Arts'],
              ['Male', 'Female'])

path = r'...'
w2v_ita = WordEmbeddingModel(KeyedVectors.load(path), 'word2vec')

path = r'...'
fast_ita_model = FastText.load_fasttext_format(path)
fast_ita = WordEmbeddingModel(fast_ita_model.wv, 'fast')

queries = [query]
models = [w2v_ita, fast_ita]
```

Here I execute the first run_queries

```python
# Run the queries using RNSB
RNSB_gender_results = run_queries(RNSB,
                                  queries,
                                  models,
                                  queries_set_name='Gender Queries')

RNSB_gender_results
```

The results were:

| model_name   |   Science and Arts wrt Male and Female |
|:-------------|---------------------------------------:|
| word2vec     |                             0.0679508  |
| fast         |                             0.00337551 |


Then, I repeated the execution:

```python
# Run the queries using RNSB
RNSB_gender_results = run_queries(RNSB,
                                  queries,
                                  models,
                                  queries_set_name='Gender Queries')

RNSB_gender_results
```

The results obtained were different.

| model_name   |   Science and Arts wrt Male and Female |
|:-------------|---------------------------------------:|
| word2vec     |                             0.0343669  |
| fast         |                             0.00310012 |



Then, use the num_iterations parameter to see if anything changes:

```python

RNSB_gender_results = run_queries(RNSB,
                                  queries,
                                  models,
                                  metric_params={'num_iterations': 5},
                                  queries_set_name='Gender Queries')

RNSB_gender_results
```

These were the results:

| model_name   |   Science and Arts wrt Male and Female |
|:-------------|---------------------------------------:|
| word2vec     |                             0.0658938  |
| fast         |                             0.00314437 |


Finally, I duplicated the same query and executed it twice using 5 iterations for each one and indicated the function to aggregate both values using abs_avg.

```python

import copy

query_2 = copy.deepcopy(query)
query_2.query_name_ = query_2.query_name_ + '_2'

queries_2 = [query, query_2]

RNSB_gender_results = run_queries(RNSB,
                                  queries_2,
                                  models,
                                  aggregate_results=True,
                                  metric_params={'num_iterations': 5},
                                  queries_set_name='Gender Queries')

RNSB_gender_results
```

This were the results:


| model_name   |   Science and Arts wrt Male and Female |   Science and Arts wrt Male and Female_2 |   RNSB: Gender Queries average of abs values score |
|:-------------|---------------------------------------:|-----------------------------------------:|---------------------------------------------------:|
| word2vec     |                             0.052708   |                               0.0421034  |                                         0.0474057  |
| fast         |                             0.00358465 |                               0.00421143 |                                         0.00389804 |


I hope this code can help you in some way.

If you are still having problems, don't doubt to ask.

Greetings,
Pablo.
